version: "3.3"
services:
  
  # the actual database
  # doesn't need to expose any port as its only used by the services in the same network
  database:
    container_name: sms_postgres_container
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test123
      PGDATA: /data/postgres
    volumes:
       - sms_db:/data/postgres
    ports:
      - "1432:5432"
    networks:
      - sms_network
    restart: unless-stopped
  
  # json importer, will import the neighboring data.json file
  json_importer:
    container_name: sms_json_importer
    build: ./database
    networks:
      - sms_network
    volumes:
      - sms_importer:/data/sms_importer
    depends_on:
      - database

  # .net core backend
  # ports are not required to be exposed, this is only done for swaggerUI
  backend:
    container_name: sms_backend
    build: ./backend
    networks:
      - sms_network
    ports:
      - "5020:5020"
    volumes:
      - sms_backend:/data/sms_backend
    depends_on:
      - database

  # react-admin frontend
  frontend:
    container_name: sms_frontend
    build: ./frontend
    networks:
      - sms_network
    ports:
      - "4020:3000"
    volumes:
      - sms_frontend:/data/sms_frontend
    depends_on:
      - backend

networks:
  sms_network:
    driver: bridge

volumes:
    sms_db:
    sms_importer:
    sms_backend:
    sms_frontend: